-- AlterTable
ALTER TABLE "DepositIntent" ALTER COLUMN "minAmount" SET DATA TYPE DECIMAL(78,0),
ALTER COLUMN "maxAmount" SET DATA TYPE DECIMAL(78,0);

-- AlterTable
ALTER TABLE "Quote" ALTER COLUMN "fromAmount" SET DATA TYPE DECIMAL(78,0),
ALTER COLUMN "estimatedFee" SET DATA TYPE DECIMAL(78,0),
ALTER COLUMN "estimatedOutput" SET DATA TYPE DECIMAL(78,0);

-- AlterTable
ALTER TABLE "SettlementConfig" ALTER COLUMN "minAmount" SET DATA TYPE DECIMAL(78,0),
ALTER COLUMN "maxAmount" SET DATA TYPE DECIMAL(78,0);
